### ISSUE TITLE
Attempting to commit closes the commit window immediately

### ISSUE THREAD

**Issue by vmalloc** [kahole/vscode-magit#108]
Probably due to a recent update, now trying to stage changes and enter commit mode causes the window to close immediately without any apparent output visible

**Comment by kahole** [comment]
Please provide more information. Which OS, vscode version, edamagit version, and steps to recreate situation.

**Comment by vmalloc** [comment]
I'm running on macOS 11.2.1 (20D74), VSCode 1.53.2, edamagit 0.6.5. 
I'm not doing anything different to what I did up until yesterday - opening a project, running magit-status, then `s` to stage changes, and then `c c` to commit. The commit window opens very very briefly and immediately closes

**Comment by vmalloc** [comment]
I also just noticed that the bottom bar shows the message "commit canceled" for a short while after this happens. Is there any way I can see why it got canceled?

**Comment by kahole** [comment]
What does the edamagit process log say?
Bring it up by pressing shift+4 from the status view after you commit gets cancelled.

**Comment by vmalloc** [comment]
Ok, I found the issue. It turns out edamagit Runs Python and my pyenv shims were not up to date, which caused it to fail. Thanks for the help and sorry for the noise!

**Comment by NamidaSai** [comment]
After updating VSCode to 1.55, I'm getting a similar bug with the commit window closing immediately before I can specify the commit message.

OS: Windows 10 Home v20H2
VSCode: v1.55
edamagit: v0.6.8
Steps to reproduce:
- open magit status
- stage all changes
- run magit.commit
- staged magit window flashes then closes instantly.
- Commit cancelled message displayed
- shift-4 edamagit process log shows the below

>'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
error: There was a problem with the editor '"C:\Program Files\Microsoft VS Code\bin\code.cmd" --wait'.
Please supply the message using either -m or -F option.


Many thanks in advance!

**Comment by kahole** [comment]
Are you able to locate the code.cmd file it's looking for.
Or something with a similar name in that folder?

**Comment by NamidaSai** [comment]
There are two files in the folder:
- code.cmd
- code (no extension)
code.cmd opens a new window of VSCode.

**Comment by kahole** [comment]
This might be related to the changes in #116 
I don't use windows, so this is hard for me to debug.
Any help is appreciated. 

@stevenguh

**Comment by stevenguh** [comment]
This doesn't look like an issue related to #116. I tested the changes against Windows both remote and non-remote.

> 'C:\Program' is not recognized as an internal or external command,

Looks like an issue related to escaping space to your vscode installation. EDIT: My install path looks something like this `C:\Users\username\AppData\Local\Programs\Microsoft VS Code`. My path has space and it still works.

What's your git version on windows?

**Comment by NamidaSai** [comment]
Thanks so much for taking the time to look into this!
git version 2.28.0.windows.1

**Comment by stevenguh** [comment]
### How commit works

magit will call git extension in vscdoe which will [spawn](https://github.com/microsoft/vscode/blob/a699ffaee62010c4634d301da2bbdb7646b8d1da/extensions/git/src/git.ts#L586) a child process with a merged env where it merges vscode process' environment and our `GIT_EDITOR` variable with the full path.

---

I tested an environment with git versions 2.27 so git version probably not it (you can also try upgrading it). I am thinking if there's something with the your inherit environment variable of your vscode instance or some UAC issue with installing vscode in program file.

Idea:

1. If you want to test if it is the recent change, you can test it by removing this [line](https://github.com/kahole/edamagit/blob/develop/src/commands/commitCommands.ts#L172). You can also do a bisect to see if there any other changes that causes this?

2. trying install vscode not in the program file?

**Comment by stevenguh** [comment]
I also tested with a system installation of vscode (to program files), it still works.

Idea:

~~1. If you want to test if it is the recent change, you can test it by removing this [line](https://github.com/kahole/edamagit/blob/develop/src/commands/commitCommands.ts#L172). You can also do a bisect to see if there any other changes that causes this?~~
~~2. trying install vscode not in the program file?~~
3. Maybe there are some issues with your environment variables like how pyenv shims were causing the issue earlier in this post.

**Comment by kahole** [comment]
Can you run this in powershell in your git repo and see what happens?
This is essentially the underlying command edamagit runs:
```
$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code.cmd" --wait'; git commit
```


---

Also you can try version 0.6.7.
No need to build it yourself, go to the Edamagit extension page in VSCode and select "Install another version"
Although I don't think this is gonna be the issue, as you say Steven.

<img width="656" alt="Screenshot 2021-04-10 at 12 23 47" src="https://user-images.githubusercontent.com/9072087/114266669-bf46eb80-99f7-11eb-8869-264609f083e1.png">

**Comment by NamidaSai** [comment]
So i've tried running the command @kahole provided in Powershell and getting the same error as the edamagit logs.

HOWEVER: switched to edamagit v0.6.7 and am now able to commit with the edamagit interface as intended.

Interestingly when running the command in powershell under v0.6.7 still gives me the same error as I had in the edamagit logs under v0.6.8. 
Lastly, tested under v0.6.9 and original issue is still happening. 
Then: updated git to v2.31.1.windows.1
Ran above tests again: same results as above.

So to conclude: last stable version for my setup is edamagit v0.6.7.

Don't know if noteworthy but: I'm also using extensions VSpaceCode (v0.9.1), Which Key (v0.8.4) and Vim (1.19.3), but since the command in powershell gives the same error not sure it's linked to those.

Thanks again for your help!

**Comment by kahole** [comment]
And if your run the one without `.cmd` at the end in powershell:
```
$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code" --wait'; git commit
```

**Comment by NamidaSai** [comment]
> And if your run the one without `.cmd` at the end in powershell:
> 
> ```
> $env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code" --wait'; git commit
> ```

This works in both v0.6.7 and v0.6.9, opening the edamagit commit message window!

**Comment by stevenguh** [comment]
Thank you for testing the setup. Basically, this command works for you
```
$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code" --wait'; git commit
```
but not this 
```
$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code.cmd" --wait'; git commit
```
---

The weird part of this is that Windows doesn't really use file `C:\Program Files\Microsoft VS Code\bin\code` because that's a bash script; however, when you call `C:\Program Files\Microsoft VS Code\bin\code` it will look for batch script `.cmd` and execute that one.

A simple experiment I ran to verify this was to open a powershell and
1. Run <code>C:\Program Files\Microsoft\` VS\` Code\bin\code</code>, it will open vscode
2. Run <code>C:\Program Files\Microsoft\` VS\` Code\bin\code</code> after renaming `code.cmd` to `code2.cmd`, it will not open vscode and ask what program to use to open the `code` file.
3. Run <code>C:\Program Files\Microsoft\` VS\` Code\bin\code</code> after renaming `code` to `code2`, it will open vscode.

However, setting git editor is a different story:
1. Run `$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code" --wait'; git commit` on a powershell, it will launch vscode
2. Run `$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code.cmd" --wait'; git commit` on a powershell, it will launch vscode
3. Run `$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code" --wait'; git commit` on a powershell after renaming `code.cmd` to `code2.cmd`, it will STILL launch vscode.
4. Run `$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code" --wait'; git commit` on a powershell after renaming `code` to `code2`, it will not launch because it failed to find `code`
5. Run `$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code" --wait';  git commit` on a powershell after emptying the content of `code` file, git commit will fail.
---

What is the error you get if you run on a powershell (not the integrated shell)
```
$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code.cmd" --wait'; git commit
```

**Comment by NamidaSai** [comment]
@stevenguh thanks for the investigation!
I ran the below command on a powershell (not integrated):
```
$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code.cmd" --wait'; git commit
```
I got the following error:
```
hint: Waiting for your editor to close the file... 'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
error: There was a problem with the editor '"C:\Program Files\Microsoft VS Code\bin\code.cmd" --wait'.
Please supply the message using either -m or -F option.
```

**Comment by stevenguh** [comment]
Okay, so basically you can reproduce outside of edamagit. Just to confirm, you can run the `code` as following without any issue in your powershell right?
```
$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code" --wait'; git commit
```


I have two thoughts on how to resolve this:
1. We can add extra checks to #116 so we only use `code.cmd` when it is on a windows remote host.
2. Continue to figure out what cause your environment to not like `code.cmd`
    - Post on either https://groups.google.com/g/git-for-windows or https://github.com/git-for-windows/git to see if anyone can explain how git commit and environmental variables are handled on Windows
    - @NamidaSai If you don't mind can you post your environment variables? like the output of `dir env:` for example.

**Comment by NamidaSai** [comment]
@stevenguh when running the below in powershell:
```
$env:GIT_EDITOR = '"C:\Program Files\Microsoft VS Code\bin\code" --wait'; git commit
```
It opens VS Code and edamagit's COMMIT_EDITMSG window as expected, so all good on that front!


Here are my environment variables:

```
ALLUSERSPROFILE                C:\ProgramData
APPDATA                        C:\Users\geoff\AppData\Roaming
ChocolateyInstall              C:\ProgramData\chocolatey
ChocolateyLastPathUpdate       132422263465660476
CommonProgramFiles             C:\Program Files\Common Files
CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files
CommonProgramW6432             C:\Program Files\Common Files
COMPUTERNAME                   SYLPHRENA
ComSpec                        C:\WINDOWS\system32\cmd.exe
DriverData                     C:\Windows\System32\Drivers\DriverData
GIT_EDITOR                     "C:\Program Files\Microsoft VS Code\bin\code" --wait
HOME                           C:\Users\geoff
HOMEDRIVE                      C:
HOMEPATH                       \Users\geoff
LOCALAPPDATA                   C:\Users\geoff\AppData\Local
LOGONSERVER                    \\SYLPHRENA
NUMBER_OF_PROCESSORS           12
OculusBase                     C:\Program Files\Oculus\
OneDrive                       C:\Users\geoff\OneDrive
OneDriveConsumer               C:\Users\geoff\OneDrive
OS                             Windows_NT
Path                           C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\...
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE         AMD64
PROCESSOR_IDENTIFIER           Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
PROCESSOR_LEVEL                6
PROCESSOR_REVISION             a502
ProgramData                    C:\ProgramData
ProgramFiles                   C:\Program Files
ProgramFiles(x86)              C:\Program Files (x86)
ProgramW6432                   C:\Program Files
PSModulePath                   C:\Users\geoff\OneDrive\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsP...
PUBLIC                         C:\Users\Public
SystemDrive                    C:
SystemRoot                     C:\WINDOWS
TEMP                           C:\Users\geoff\AppData\Local\Temp
TMP                            C:\Users\geoff\AppData\Local\Temp
USERDOMAIN                     SYLPHRENA
USERDOMAIN_ROAMINGPROFILE      SYLPHRENA
USERNAME                       geoff
USERPROFILE                    C:\Users\geoff
windir                         C:\WINDOWS
```

**Comment by stevenguh** [comment]
I don't see any abnormality. Since the path is truncated, 
1. can you check your PATH environment variable to see if there's any quoting issue?
2. or missing `/r` character?
3. Any git hook in the repo? Have you tried it on other repo?

REF: https://superuser.com/questions/119610/spaces-and-parenthesis-in-windows-path-variable-screws-up-batch-files
REF: https://github.com/Azure/azure-cli/issues/9204#issuecomment-508751252
REF: https://github.com/Cosium/git-code-format-maven-plugin/issues/53

I am not still sure what's the issue with `.cmd`. Another way to workaround this is like I mentioned before which gates `.cmd` for remote window server only like https://github.com/kahole/edamagit/pull/123. (I haven't tested it yet)

**Comment by NamidaSai** [comment]
Thank you @stevenguh. I've looked at the Path env. variable and the referenced links, but can't find anything odd there. Pasted here in case I missed something (edit: added \n for readability):

```
C:\Program Files (x86)\Razer Chroma SDK\bin;
C:\Program Files\Razer Chroma SDK\bin;
C:\Program Files (x86)\Razer\ChromaBroadcast\bin;
C:\Program Files\Razer\ChromaBroadcast\bin;
C:\Program Files\Oculus\Support\oculus-runtime;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\ProgramData\chocolatey\bin;
C:\Program Files\Microsoft VS Code\bin;
C:\Program Files\dotnet\;
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;
C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;
C:\Program Files (x86)\dotnet\;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\WINDOWS\System32\OpenSSH\;
C:\Program Files\Git\cmd;
C:\Users\geoff\AppData\Local\Microsoft\WindowsApps;
C:\Users\geoff\.dotnet\tools;
C:\Program Files\LLVM\bin;
C:\MinGW\bin;
C:\Users\geoff\AppData\Local\GitHubDesktop\bin;
C:\Users\geoff\AppData\Local\Microsoft\WindowsApps
```

Also, no git hooks in the repo and the issue is not repo specific.

**Comment by stevenguh** [comment]
Shouldn't the the path with space be wrapped in double quote?

btw I marked the PR as ready to review since I tested it on both remote and non-remote Windows environment, and it can be a quick fix to this.

**Comment by kahole** [comment]
v0.6.11 released with Steven's fix

**Comment by NamidaSai** [comment]
Thank you both @stevenguh and @kahole for your help and your hard work, really appreciate it!

**Comment by edelvalle** [comment]
I'm having this problem still... I have

edamagit: v0.6.11
vscodium: v1.56.2
OS: Manjaro x86 64bit v21.0.4

What was the fix you did, so I can see if I can look into it, reproduce the error, understand why and make a PR

**Comment by rami3l** [comment]
This breaks in macOS 12.3 since `python` cannot be found (Python 2 got removed)...

```txt
[run] git log --format=%H%d [%an] [%at]%s --use-mailmap -n256 --graph master --
[1] git commit --amend --only
/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code: line 6: python: command not found
/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code: line 10: ./MacOS/Electron: No such file or directory
error: There was a problem with the editor '"/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code" --wait'.
Please supply the message using either -m or -F option.
```

---

Update: There's actually a workaround involving editing `/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code` (which is a `bash` script calling `python`).
For more details, see: https://github.com/microsoft/vscode/issues/134635#issuecomment-1027734972
