### ISSUE TITLE
Staging from diff view?

### ISSUE THREAD

**Issue by Xuerian** [kahole/vscode-magit#128]
I'm a new (ed)magit user, so maybe I'm just missing something obvious in the workflow.

I've opened a diff for a given file, and would like to stage hunks or selected lines directly from the "diff.magit" view.

Is this already possible?

**Comment by kahole** [comment]
Hi, this is not possible due to the fact that the changes in the diff might not apply to the current state of the repo. (The diff could be old changes, or changes from another branch, etc)

At least that's my take on it, I haven't checked what emacs magit does here.

**Comment by Xuerian** [comment]
Aha, I can understand the cases where it wouldn't work, thanks.

**Comment by daroczig** [comment]
First of all, thanks a ton for this great VS Code extension :bow: 

I'm coming from Emacs and really miss this feature from magit: being able to stage lines in the diff view, and the other way around as well (looking at the staged diff and unstage from there).

I understand that this is to be done in edamagit in the main `status.magit`, but expanding all files is less convenient than doing these ops in a separate buffer (probably mainly due to what I got used to in emacs).
