### ISSUE TITLE
Reuse existing status buffer

### ISSUE THREAD

**Issue by jtrakk** [kahole/vscode-magit#143]
When I'm editing text and I have a status buffer open in another pane, doing magit-status opens a second status buffer instead of focusing the original. Emacs Magit focuses the original, which I prefer.

**Comment by kahole** [comment]
Could you please describe this issue in greater detail, as for most case it does re-use the existing editor.

One known case is when you have another tab open in the same pane as the status view, it is unable to recover the unfocused edamagit tab. This is because the vscode APIs cannot guarantee that this tab hasn't already been closed, and is waiting to be garbage collected.
But please expand on your issue and I'll investigate.

**Comment by jtrakk** [comment]
I can't reproduce this problem anymore. I'll reopen if I can find a reproducible example.
